package com.tanujnotes.leiconpack.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF507DA4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDDF1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF00355D)
val md_theme_light_secondary = Color(0xFF5B6B71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDEEFF8)
val md_theme_light_onSecondaryContainer = Color(0xFF19202B)
val md_theme_light_tertiary = Color(0xFF526E7D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD8F3FF)
val md_theme_light_onTertiaryContainer = Color(0xFF31111D)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFDCE6F9)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_outline = Color(0xFF74797E)
val md_theme_light_background = Color(0xFFFBFFFF)
val md_theme_light_onBackground = Color(0xFF1B1D1F)
val md_theme_light_surface = Color(0xFFFBFFFF)
val md_theme_light_onSurface = Color(0xFF1B1E1F)
val md_theme_light_surfaceVariant = Color(0xFFE0ECEC)
val md_theme_light_onSurfaceVariant = Color(0xFF454B4F)
val md_theme_light_inverseSurface = Color(0xFF303233)
val md_theme_light_inverseOnSurface = Color(0xFFEFF4F3)
val md_theme_light_inversePrimary = Color(0xFFBCE4FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF5093A4)
val md_theme_light_outlineVariant = Color(0xFFCAC4D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFBCE2FF)
val md_theme_dark_onPrimary = Color(0xFF1E4B72)
val md_theme_dark_primaryContainer = Color(0xFF37678B)
val md_theme_dark_onPrimaryContainer = Color(0xFFDDF4FF)
val md_theme_dark_secondary = Color(0xFFC2D4DC)
val md_theme_dark_onSecondary = Color(0xFF2D3241)
val md_theme_dark_secondaryContainer = Color(0xFF444E58)
val md_theme_dark_onSecondaryContainer = Color(0xFFDEF0F8)
val md_theme_dark_tertiary = Color(0xFFB8EFDC)
val md_theme_dark_onTertiary = Color(0xFF492532)
val md_theme_dark_tertiaryContainer = Color(0xFF633B48)
val md_theme_dark_onTertiaryContainer = Color(0xFFD8EAFF)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFDCF5F9)
val md_theme_dark_outline = Color(0xFF8F9699)
val md_theme_dark_background = Color(0xFF161A1A)
val md_theme_dark_onBackground = Color(0xFFE1E4E6)
val md_theme_dark_surface = Color(0xFF131516)
val md_theme_dark_onSurface = Color(0xFFE1E5E6)
val md_theme_dark_surfaceVariant = Color(0xFF262C2C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4D0CD)
val md_theme_dark_inverseSurface = Color(0xFFE1E4E6)
val md_theme_dark_inverseOnSurface = Color(0xFF202222)
val md_theme_dark_inversePrimary = Color(0xFF5080A4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFBCDCFF)
val md_theme_dark_outlineVariant = Color(0xFF45494F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF5080A4)
